// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvcUrzBGpXUgTa6FuiUJXlBWUTb5QOs-k',
    appId: '1:132845397292:web:6c3366285921395f6c3889',
    messagingSenderId: '132845397292',
    projectId: 'karat-hive-app',
    authDomain: 'karat-hive-app.firebaseapp.com',
    storageBucket: 'karat-hive-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Wld2fyrVtkld6Ab2BVRd5kSL81c7GM4',
    appId: '1:132845397292:android:53d6808d53eae29c6c3889',
    messagingSenderId: '132845397292',
    projectId: 'karat-hive-app',
    storageBucket: 'karat-hive-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA1cpg1DRVSyccWVREhgDWL0-fjKjDk6A',
    appId: '1:132845397292:ios:f6e1eb7bd2d2d0bb6c3889',
    messagingSenderId: '132845397292',
    projectId: 'karat-hive-app',
    storageBucket: 'karat-hive-app.firebasestorage.app',
    iosBundleId: 'com.kh.hiveAdmin',
  );
}
