/** Closed enumeration from docs/API-Route-Inventory.md §5. Expand, never reuse. */
export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_REUSE_DETECTED: 'REFRESH_REUSE_DETECTED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL: 'INTERNAL',

  // --- identity / auth (vendor onboarding vertical) ---
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  MOBILE_ALREADY_REGISTERED: 'MOBILE_ALREADY_REGISTERED',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  LICENCE_ALREADY_REGISTERED: 'LICENCE_ALREADY_REGISTERED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
  PASSWORD_POLICY: 'PASSWORD_POLICY',

  // --- vendor lifecycle ---
  VENDOR_NOT_ACTIVE: 'VENDOR_NOT_ACTIVE',
  ILLEGAL_VENDOR_TRANSITION: 'ILLEGAL_VENDOR_TRANSITION',

  // --- media ---
  MEDIA_TYPE_REJECTED: 'MEDIA_TYPE_REJECTED',
  MEDIA_QUARANTINED: 'MEDIA_QUARANTINED',
  MEDIA_NOT_READY: 'MEDIA_NOT_READY',
  UPLOAD_NOT_COMPLETED: 'UPLOAD_NOT_COMPLETED',

  // --- taxonomy ---
  TAXONOMY_IN_USE: 'TAXONOMY_IN_USE',

  // --- requests, offers, connections ---
  OAUTH_REQUIRED: 'OAUTH_REQUIRED',
  REQUEST_NOT_PUBLISHABLE: 'REQUEST_NOT_PUBLISHABLE',
  BULLION_BELOW_MINIMUM: 'BULLION_BELOW_MINIMUM',
  GOLD_RATE_UNAVAILABLE: 'GOLD_RATE_UNAVAILABLE',
  CONCURRENT_REQUEST_LIMIT: 'CONCURRENT_REQUEST_LIMIT',
  STRUCTURAL_FIELD_IMMUTABLE: 'STRUCTURAL_FIELD_IMMUTABLE',
  REQUEST_NOT_CANCELLABLE: 'REQUEST_NOT_CANCELLABLE',
  CONTACT_DETAILS_IN_TEXT: 'CONTACT_DETAILS_IN_TEXT',
  NOT_IN_MATCH_SET: 'NOT_IN_MATCH_SET',
  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
  OFFER_NOT_OPEN: 'OFFER_NOT_OPEN',
  OFFER_ALREADY_PENDING: 'OFFER_ALREADY_PENDING',
  OFFER_REVISION_LIMIT: 'OFFER_REVISION_LIMIT',
  OFFER_NOT_PENDING: 'OFFER_NOT_PENDING',
  OFFER_EXPIRED: 'OFFER_EXPIRED',
  OFFER_ALREADY_ACCEPTED: 'OFFER_ALREADY_ACCEPTED',
  CONNECTION_CLOSED: 'CONNECTION_CLOSED',
  NOT_A_PARTY: 'NOT_A_PARTY',

  // --- reviews & abuse ---
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
  REVIEW_EDIT_WINDOW_CLOSED: 'REVIEW_EDIT_WINDOW_CLOSED',

  // --- admin & settings ---
  SETTING_OUT_OF_RANGE: 'SETTING_OUT_OF_RANGE',
  EXPORT_IN_PROGRESS: 'EXPORT_IN_PROGRESS',
  ADMIN_SELF_REGISTRATION_FORBIDDEN: 'ADMIN_SELF_REGISTRATION_FORBIDDEN',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
