/** Closed enumeration from docs/API-Route-Inventory.md §5. Expand, never reuse. */
export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_REUSE_DETECTED: 'REFRESH_REUSE_DETECTED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL: 'INTERNAL',

  // --- identity / auth (vendor onboarding vertical) ---
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  MOBILE_ALREADY_REGISTERED: 'MOBILE_ALREADY_REGISTERED',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  LICENCE_ALREADY_REGISTERED: 'LICENCE_ALREADY_REGISTERED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',

  // --- vendor lifecycle ---
  VENDOR_NOT_ACTIVE: 'VENDOR_NOT_ACTIVE',
  ILLEGAL_VENDOR_TRANSITION: 'ILLEGAL_VENDOR_TRANSITION',

  // --- media ---
  MEDIA_TYPE_REJECTED: 'MEDIA_TYPE_REJECTED',
  MEDIA_QUARANTINED: 'MEDIA_QUARANTINED',
  MEDIA_NOT_READY: 'MEDIA_NOT_READY',
  UPLOAD_NOT_COMPLETED: 'UPLOAD_NOT_COMPLETED',

  // --- taxonomy ---
  TAXONOMY_IN_USE: 'TAXONOMY_IN_USE',

  // --- subscriptions ---
  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',

  // --- requests & offers ---
  REQUEST_NOT_PUBLISHABLE: 'REQUEST_NOT_PUBLISHABLE',
  BULLION_BELOW_MINIMUM: 'BULLION_BELOW_MINIMUM',
  GOLD_RATE_UNAVAILABLE: 'GOLD_RATE_UNAVAILABLE',
  CONCURRENT_REQUEST_LIMIT: 'CONCURRENT_REQUEST_LIMIT',
  STRUCTURAL_FIELD_IMMUTABLE: 'STRUCTURAL_FIELD_IMMUTABLE',
  CONTACT_DETAILS_IN_TEXT: 'CONTACT_DETAILS_IN_TEXT',
  OAUTH_REQUIRED: 'OAUTH_REQUIRED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
