/* Route table for all 67 screens */
window.KH_NAV = {
  customer: {
    default: "CUS-S02",
    tabs: [
      { id: "home", label: "Home", icon: "⌂", screen: "CUS-S02" },
      { id: "requests", label: "Requests", icon: "▤", screen: "CUS-S10" },
      { id: "connections", label: "Connections", icon: "◎", screen: "CUS-S16" },
      { id: "notifications", label: "Alerts", icon: "✧", screen: "CUS-S19" },
      { id: "profile", label: "Profile", icon: "◯", screen: "CUS-S20" },
    ],
    screens: [
      { id: "CUS-S01", file: "CUS-S01-onboarding.html", title: "Onboarding", parent: null },
      { id: "CUS-S02", file: "CUS-S02-home.html", title: "Home", parent: null },
      { id: "CUS-S03", file: "CUS-S03-request-type-selection.html", title: "Request type", parent: "CUS-S02" },
      { id: "CUS-S04", file: "CUS-S04-create-find-ornament.html", title: "Find an ornament", parent: "CUS-S03" },
      { id: "CUS-S05", file: "CUS-S05-create-sell-old-gold.html", title: "Sell old gold", parent: "CUS-S03" },
      { id: "CUS-S06", file: "CUS-S06-create-gold-coins.html", title: "Gold coins", parent: "CUS-S03" },
      { id: "CUS-S07", file: "CUS-S07-create-gold-bullion.html", title: "Gold bullion", parent: "CUS-S03" },
      { id: "CUS-S08", file: "CUS-S08-image-capture.html", title: "Images", parent: "CUS-S04" },
      { id: "CUS-S09", file: "CUS-S09-request-review-publish.html", title: "Review & publish", parent: "CUS-S04" },
      { id: "CUS-S10", file: "CUS-S10-request-detail.html", title: "Request detail", parent: "CUS-S02" },
      { id: "CUS-S11", file: "CUS-S11-offers-list.html", title: "Offers", parent: "CUS-S10" },
      { id: "CUS-S12", file: "CUS-S12-offer-comparison.html", title: "Compare offers", parent: "CUS-S11" },
      { id: "CUS-S13", file: "CUS-S13-offer-detail.html", title: "Offer detail", parent: "CUS-S11" },
      { id: "CUS-S14", file: "CUS-S14-accept-confirmation.html", title: "Mark as interested", parent: "CUS-S13" },
      { id: "CUS-S15", file: "CUS-S15-connection-detail.html", title: "Connection", parent: "CUS-S16" },
      { id: "CUS-S16", file: "CUS-S16-connections-list.html", title: "Connections", parent: null },
      { id: "CUS-S17", file: "CUS-S17-history.html", title: "History", parent: "CUS-S20" },
      { id: "CUS-S18", file: "CUS-S18-leave-review.html", title: "Leave review", parent: "CUS-S15" },
      { id: "CUS-S19", file: "CUS-S19-notification-centre.html", title: "Notifications", parent: null },
      { id: "CUS-S20", file: "CUS-S20-profile.html", title: "Profile", parent: null },
      { id: "CUS-S21", file: "CUS-S21-settings.html", title: "Settings", parent: "CUS-S20" },
      { id: "CUS-S22", file: "CUS-S22-report-abuse.html", title: "Report abuse", parent: "CUS-S15" },
    ],
  },
  vendor: {
    default: "VEN-S05",
    tabs: [
      { id: "dashboard", label: "Home", icon: "⌂", screen: "VEN-S05" },
      { id: "requests", label: "Requests", icon: "▤", screen: "VEN-S06" },
      { id: "offers", label: "Offers", icon: "◇", screen: "VEN-S11" },
      { id: "connections", label: "Connect", icon: "◎", screen: "VEN-S12" },
      { id: "more", label: "More", icon: "⋯", screen: "VEN-S15" },
    ],
    screens: [
      { id: "VEN-S01", file: "VEN-S01-registration.html", title: "Registration", parent: null },
      { id: "VEN-S02", file: "VEN-S02-kyc-document-upload.html", title: "KYC upload", parent: "VEN-S01" },
      { id: "VEN-S03", file: "VEN-S03-awaiting-approval.html", title: "Awaiting approval", parent: null, restricted: true },
      { id: "VEN-S04", file: "VEN-S04-login.html", title: "Vendor login", parent: null },
      { id: "VEN-S05", file: "VEN-S05-dashboard.html", title: "Dashboard", parent: null },
      { id: "VEN-S06", file: "VEN-S06-available-requests.html", title: "Available requests", parent: null },
      { id: "VEN-S07", file: "VEN-S07-request-filters.html", title: "Filters", parent: "VEN-S06" },
      { id: "VEN-S08", file: "VEN-S08-request-detail.html", title: "Request detail", parent: "VEN-S06" },
      { id: "VEN-S09", file: "VEN-S09-submit-offer.html", title: "Submit offer", parent: "VEN-S08" },
      { id: "VEN-S10", file: "VEN-S10-revise-withdraw-offer.html", title: "Revise / withdraw", parent: "VEN-S11" },
      { id: "VEN-S11", file: "VEN-S11-my-offers.html", title: "My offers", parent: null },
      { id: "VEN-S12", file: "VEN-S12-connections-list.html", title: "Connections", parent: null },
      { id: "VEN-S13", file: "VEN-S13-connection-detail.html", title: "Connection detail", parent: "VEN-S12" },
      { id: "VEN-S14", file: "VEN-S14-offer-history.html", title: "Offer history", parent: "VEN-S15" },
      { id: "VEN-S15", file: "VEN-S15-business-profile.html", title: "Business profile", parent: null },
      { id: "VEN-S16", file: "VEN-S16-categories-regions.html", title: "Categories & regions", parent: "VEN-S15" },
      { id: "VEN-S17", file: "VEN-S17-notification-centre.html", title: "Notifications", parent: null },
      { id: "VEN-S18", file: "VEN-S18-settings.html", title: "Settings", parent: "VEN-S15" },
      { id: "VEN-S19", file: "VEN-S19-leave-customer-feedback.html", title: "Customer feedback", parent: "VEN-S13" },
      { id: "VEN-S20", file: "VEN-S20-my-reviews.html", title: "My reviews", parent: "VEN-S15" },
      { id: "VEN-S21", file: "VEN-S21-report-abuse.html", title: "Report abuse", parent: "VEN-S13" },
      { id: "VEN-S22", file: "VEN-S22-subscription.html", title: "Subscription", parent: "VEN-S15" },
    ],
  },
  admin: {
    default: "ADM-S02",
    screens: [
      { id: "ADM-S01", file: "ADM-S01-login.html", title: "Admin login", parent: null },
      { id: "ADM-S02", file: "ADM-S02-dashboard.html", title: "Dashboard", parent: null },
      { id: "ADM-S03", file: "ADM-S03-customer-list.html", title: "Customers", parent: null },
      { id: "ADM-S04", file: "ADM-S04-customer-detail.html", title: "Customer detail", parent: "ADM-S03" },
      { id: "ADM-S05", file: "ADM-S05-vendor-list.html", title: "Vendors", parent: null },
      { id: "ADM-S06", file: "ADM-S06-vendor-detail.html", title: "Vendor detail", parent: "ADM-S05" },
      { id: "ADM-S07", file: "ADM-S07-verification-queue.html", title: "Verification queue", parent: null },
      { id: "ADM-S08", file: "ADM-S08-request-list.html", title: "Requests", parent: null },
      { id: "ADM-S09", file: "ADM-S09-request-detail.html", title: "Request detail", parent: "ADM-S08" },
      { id: "ADM-S10", file: "ADM-S10-offer-list.html", title: "Offers", parent: null },
      { id: "ADM-S11", file: "ADM-S11-offer-detail.html", title: "Offer detail", parent: "ADM-S10" },
      { id: "ADM-S12", file: "ADM-S12-connection-list.html", title: "Connections", parent: null },
      { id: "ADM-S13", file: "ADM-S13-connection-detail.html", title: "Connection detail", parent: "ADM-S12" },
      { id: "ADM-S14", file: "ADM-S14-category-management.html", title: "Categories", parent: null },
      { id: "ADM-S15", file: "ADM-S15-region-management.html", title: "Regions", parent: null },
      { id: "ADM-S16", file: "ADM-S16-review-moderation.html", title: "Review moderation", parent: null },
      { id: "ADM-S17", file: "ADM-S17-reports-analytics.html", title: "Reports", parent: null },
      { id: "ADM-S18", file: "ADM-S18-announcement-composer.html", title: "Announcements", parent: null },
      { id: "ADM-S19", file: "ADM-S19-platform-settings.html", title: "Platform settings", parent: null },
      { id: "ADM-S20", file: "ADM-S20-gold-rate-configuration.html", title: "Gold rates", parent: null },
      { id: "ADM-S21", file: "ADM-S21-abuse-report-queue.html", title: "Abuse reports", parent: null },
      { id: "ADM-S22", file: "ADM-S22-audit-log.html", title: "Audit log", parent: null },
      { id: "ADM-S23", file: "ADM-S23-admin-user-management.html", title: "Admin users", parent: null },
    ],
  },
};

window.KH_NAV.find = function (role, screenId) {
  const pack = window.KH_NAV[role];
  if (!pack) return null;
  return pack.screens.find((s) => s.id === screenId) || null;
};
